"""empty message

Revision ID: 21832528d100
Revises: f9a1320a1726
Create Date: 2021-04-07 13:50:40.501083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21832528d100'
down_revision = 'f9a1320a1726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('iamge_url', sa.String(length=256), nullable=True),
    sa.Column('doc_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
