"""empty message

Revision ID: 3bfd9054f55c
Revises: 10b995e393f1
Create Date: 2021-09-22 16:18:30.642438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfd9054f55c'
down_revision = '10b995e393f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('account_name', sa.String(length=1000), nullable=True))
    op.add_column('reports', sa.Column('password', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'password')
    op.drop_column('reports', 'account_name')
    # ### end Alembic commands ###
