"""empty message

Revision ID: 48dfba27a952
Revises: b49e7c518ac7
Create Date: 2021-04-19 17:19:22.700260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dfba27a952'
down_revision = 'b49e7c518ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_details', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('strategy_details', sa.Boolean(), nullable=True))
    op.drop_column('users', 'update')
    op.drop_column('users', 'write')
    op.drop_column('users', 'delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('write', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('update', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'strategy_details')
    op.drop_column('users', 'client_details')
    # ### end Alembic commands ###
