"""empty message

Revision ID: 4ffb572ce912
Revises: dec0aeb2193e
Create Date: 2021-05-15 17:54:21.091649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffb572ce912'
down_revision = 'dec0aeb2193e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
