"""empty message

Revision ID: 5013ddf3037e
Revises: 48dfba27a952
Create Date: 2021-04-20 14:49:27.546766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5013ddf3037e'
down_revision = '48dfba27a952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crn', sa.String(length=1000), nullable=True),
    sa.Column('company', sa.String(length=1000), nullable=True),
    sa.Column('data', sa.String(length=10000), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
