"""empty message

Revision ID: 59ddeb84c2a3
Revises: f6c4b8e12559
Create Date: 2021-04-16 16:37:19.120460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ddeb84c2a3'
down_revision = 'f6c4b8e12559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
