"""empty message

Revision ID: 65facbeeaafa
Revises: 77e7c1661ddd
Create Date: 2021-09-23 15:33:39.649552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65facbeeaafa'
down_revision = '77e7c1661ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reports', ['account_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='unique')
    # ### end Alembic commands ###
