"""empty message

Revision ID: 77e7c1661ddd
Revises: 3bfd9054f55c
Create Date: 2021-09-22 18:35:11.964910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e7c1661ddd'
down_revision = '3bfd9054f55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('capital', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'capital')
    # ### end Alembic commands ###
