"""empty message

Revision ID: aad3f45effe2
Revises: 21832528d100
Create Date: 2021-04-08 14:01:04.383595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad3f45effe2'
down_revision = '21832528d100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
