"""empty message

Revision ID: b49e7c518ac7
Revises: 59ddeb84c2a3
Create Date: 2021-04-17 13:47:41.372525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49e7c518ac7'
down_revision = '59ddeb84c2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('note', sa.String(length=2000), nullable=True))
    op.add_column('reports', sa.Column('script', sa.String(length=1000), nullable=True))
    op.add_column('reports', sa.Column('timestamp', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'timestamp')
    op.drop_column('reports', 'script')
    op.drop_column('reports', 'note')
    # ### end Alembic commands ###
