"""empty message

Revision ID: ca70e18d0154
Revises: cf7fc801babc
Create Date: 2021-04-08 14:06:28.017992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca70e18d0154'
down_revision = 'cf7fc801babc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
