"""empty message

Revision ID: d1450eb4f76d
Revises: 686e8180c3d0
Create Date: 2021-05-27 14:59:27.877154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1450eb4f76d'
down_revision = '686e8180c3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('profit_date', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('upload_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'upload_date')
    op.drop_column('clients', 'profit_date')
    # ### end Alembic commands ###
