"""empty message

Revision ID: d1ca69de3d5e
Revises: e3badb6fe5c1
Create Date: 2021-04-10 14:27:15.663567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1ca69de3d5e'
down_revision = 'e3badb6fe5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('live_streaming', sa.String(length=256), nullable=True))
    op.add_column('reports', sa.Column('setting_img', postgresql.ARRAY(sa.String(length=256)), nullable=True))
    op.add_column('reports', sa.Column('telegram_channel', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'telegram_channel')
    op.drop_column('reports', 'setting_img')
    op.drop_column('reports', 'live_streaming')
    # ### end Alembic commands ###
