"""empty message

Revision ID: df08bedb1de3
Revises: 65facbeeaafa
Create Date: 2021-12-20 15:09:38.210653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df08bedb1de3'
down_revision = '65facbeeaafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('profitable_category', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'profitable_category')
    # ### end Alembic commands ###
