"""empty message

Revision ID: e7d782b582f6
Revises: 40bfe2998b67
Create Date: 2021-04-14 12:46:33.542594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d782b582f6'
down_revision = '40bfe2998b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('update', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('write', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'write')
    op.drop_column('users', 'update')
    op.drop_column('users', 'delete')
    # ### end Alembic commands ###
