"""empty message

Revision ID: f6c4b8e12559
Revises: e7d782b582f6
Create Date: 2021-04-15 18:33:16.499450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6c4b8e12559'
down_revision = 'e7d782b582f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('strategy_date', sa.DateTime(), nullable=True))
    op.drop_column('reports', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'strategy_date')
    op.drop_column('reports', 'date_created')
    # ### end Alembic commands ###
