"""empty message

Revision ID: f7cee81ef359
Revises: 5013ddf3037e
Create Date: 2021-04-20 16:46:20.737837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cee81ef359'
down_revision = '5013ddf3037e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'date_updated')
    op.drop_column('clients', 'date_created')
    # ### end Alembic commands ###
