"""empty message

Revision ID: f9a1320a1726
Revises: 
Create Date: 2021-03-31 13:03:51.306300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a1320a1726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('strategy_name', sa.String(length=256), nullable=True),
    sa.Column('account_number', sa.Integer(), nullable=True),
    sa.Column('broker_name', sa.String(length=256), nullable=True),
    sa.Column('server', sa.String(length=256), nullable=True),
    sa.Column('investor', sa.String(length=256), nullable=True),
    sa.Column('profitable', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('max_lot', sa.String(length=256), nullable=True),
    sa.Column('max_m2m', sa.Integer(), nullable=True),
    sa.Column('working_live', sa.String(length=256), nullable=True),
    sa.Column('back_test_report', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
